# Generated by Django 4.2.7 on 2025-11-27 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('user', 'Regular User'), ('staff', 'Staff Member')], default='staff', max_length=10),
        ),
    ]
