# Generated by Django 4.2.7 on 2025-11-30 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_boardmember_is_active_corevalue_is_active_and_more'),
    ]

    operations = [
    ]
