# Generated by Django 4.2.7 on 2025-11-30 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
