# Generated by Django 4.2.7 on 2025-11-30 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_contactmessage_resolved'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesetting',
            name='copyright_text',
            field=models.CharField(default='© 2025 Youth Shield Foundation. All rights reserved.', help_text='Copyright notice', max_length=200),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='description',
            field=models.TextField(blank=True, help_text='Brief organization description', null=True),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='emergency_phone',
            field=models.CharField(blank=True, help_text='Emergency contact number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Facebook page URL', null=True),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Instagram profile URL', null=True),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='LinkedIn page URL', null=True),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='support_email',
            field=models.EmailField(blank=True, help_text='Support email address', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='tagline',
            field=models.CharField(blank=True, help_text='Short tagline or slogan', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='tiktok_url',
            field=models.URLField(blank=True, help_text='TikTok profile URL', null=True),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='twitter_url',
            field=models.URLField(blank=True, help_text='Twitter/X profile URL', null=True),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='website_url',
            field=models.URLField(blank=True, help_text='Official website URL', null=True),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='whatsapp_channel_url',
            field=models.URLField(blank=True, help_text='WhatsApp channel URL', null=True),
        ),
    ]
