# Generated by Django 4.2.7 on 2025-12-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_websitesetting_copyright_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesetting',
            name='Registration_Number',
            field=models.CharField(default='S/NO 1234/5678/90', max_length=100, unique=True),
        ),
    ]
