# Generated by Django 4.2.7 on 2025-12-16 18:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_websitesetting_registration_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='executivecommittee',
            options={'ordering': ['display_order', 'name']},
        ),
        migrations.RenameField(
            model_name='executivecommittee',
            old_name='order',
            new_name='display_order',
        ),
        migrations.AddField(
            model_name='executivecommittee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='executivecommittee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='executivecommittee',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='executivecommittee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='executivecommittee',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='executivecommittee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='executive/'),
        ),
    ]
