# Generated by Django 4.2.7 on 2026-01-03 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_executivecommittee_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesetting',
            name='default_language',
            field=models.CharField(default='en', help_text="Default language code (e.g., 'en', 'sw')", max_length=10),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='footer_text',
            field=models.TextField(blank=True, help_text='Additional footer text', null=True),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='google_analytics_id',
            field=models.CharField(blank=True, help_text='Google Analytics tracking ID', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='maintenance_mode',
            field=models.BooleanField(default=False, help_text='Enable maintenance mode'),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Meta description for SEO', null=True),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords for SEO', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Page title for SEO', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='privacy_policy_url',
            field=models.URLField(blank=True, help_text='Privacy policy page URL', null=True),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='terms_of_service_url',
            field=models.URLField(blank=True, help_text='Terms of service page URL', null=True),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='timezone',
            field=models.CharField(default='Africa/Nairobi', help_text='Timezone for the organization', max_length=50),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='working_hours',
            field=models.CharField(blank=True, help_text='Working hours information', max_length=200, null=True),
        ),
    ]
