# Generated by Django 4.2.7 on 2026-01-02 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('frequency', models.CharField(choices=[('disabled', 'Disabled'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='disabled', max_length=20)),
                ('backup_time', models.TimeField(default='02:00')),
                ('criteria', models.CharField(choices=[('time', 'Time-based'), ('size', 'Database Size Change'), ('activity', 'User Activity'), ('manual', 'Manual Trigger')], default='time', max_length=20)),
                ('size_threshold', models.PositiveIntegerField(default=100, help_text='Size threshold in MB for size-based backups')),
                ('activity_threshold', models.PositiveIntegerField(default=100, help_text='Number of new records for activity-based backups')),
                ('max_backups', models.PositiveIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BackupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Backup Created'), ('deleted', 'Backup Deleted'), ('downloaded', 'Backup Downloaded'), ('failed', 'Backup Failed'), ('scheduled', 'Backup Scheduled')], max_length=20)),
                ('message', models.TextField()),
                ('backup_file', models.CharField(blank=True, max_length=255, null=True)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff_dashboard.backupjob')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
