# Generated by Django 4.2.7 on 2026-01-03 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('view', 'Page View'), ('create', 'Create Record'), ('update', 'Update Record'), ('delete', 'Delete Record'), ('export', 'Export Data'), ('import', 'Import Data'), ('backup', 'Backup Operation'), ('settings', 'Settings Change'), ('other', 'Other Action')], default='other', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=500)),
                ('method', models.CharField(blank=True, max_length=10)),
                ('details', models.JSONField(blank=True, help_text='Additional details about the action', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string from browser')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='staff_dashb_user_id_2406f2_idx'), models.Index(fields=['action', 'timestamp'], name='staff_dashb_action_94c944_idx'), models.Index(fields=['ip_address'], name='staff_dashb_ip_addr_8fefa1_idx')],
            },
        ),
    ]
