# Generated by Django 4.2.7 on 2025-11-28 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='objective',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
