# Generated by Django 4.2.7 on 2025-11-30 17:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0003_remove_testimonial_one_testimonial_per_user_per_day_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='testimonial',
            name='one_testimonial_per_user_per_day',
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='testimonial',
            constraint=models.UniqueConstraint(condition=models.Q(('created_at__date', datetime.date(2025, 11, 30))), fields=('user',), name='one_testimonial_per_user_per_day'),
        ),
    ]
