# Generated by Django 4.2.7 on 2025-12-06 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0007_remove_testimonial_one_testimonial_per_user_per_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
