# Generated by Django 4.2.7 on 2025-12-07 19:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0008_testimonial_position'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='testimonial',
            name='one_testimonial_per_user_per_day',
        ),
        migrations.AddConstraint(
            model_name='testimonial',
            constraint=models.UniqueConstraint(condition=models.Q(('created_at__date', datetime.date(2025, 12, 7))), fields=('user',), name='one_testimonial_per_user_per_day'),
        ),
    ]
