# Generated by Django 4.2.7 on 2026-01-01 10:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0012_remove_testimonial_one_testimonial_per_user_per_day_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='testimonial',
            name='one_testimonial_per_user_per_day',
        ),
        migrations.AddConstraint(
            model_name='testimonial',
            constraint=models.UniqueConstraint(condition=models.Q(('created_at__date', datetime.date(2026, 1, 1))), fields=('user',), name='one_testimonial_per_user_per_day'),
        ),
    ]
