# Generated by Django 4.2.7 on 2026-01-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0013_remove_testimonial_one_testimonial_per_user_per_day_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='testimonial',
            name='one_testimonial_per_user_per_day',
        ),
        migrations.AddConstraint(
            model_name='testimonial',
            constraint=models.UniqueConstraint(fields=('user',), name='one_testimonial_per_user'),
        ),
    ]
